import ImgPropertyFront from './assets/images/property-image-1.webp';
import ImgPropertySide from './assets/images/property-image-2.webp';
import ImgPropertyRear from './assets/images/property-image-3.webp';
import ImgPropertyYard from './assets/images/property-image-4.webp';

export const PROPERTIESDATA = [
  {
    id: 1,
    street: '29 Becker Center',
    city: 'Louisville',
    country: 'United States',
    state: 'Kentucky',
    price: 2232795,
    bed: 3,
    bath: 1,
    sqft: 4997,
    uniqueId: '67467651fc13ae3c43e1c26f',
    image:
      'http://ap.rdcpix.com/dc056cce79810cd4113cadea6618982dl-m526987112rd-w2048_h1536.webp',
    photos: [
      { id: 1, title: 'front', image: ImgPropertyFront },
      { id: 2, title: 'side', image: ImgPropertySide },
      { id: 3, title: 'rear', image: ImgPropertyRear },
      { id: 4, title: 'yard', image: ImgPropertyYard },
    ],
    detail:
      'The house has 4 bedrooms and 2 bathrooms with ample rental potential. Qualifies for AHA program that allows $2700 month rent. Spacious room sizes, separate laundry room, huge deck on rear, additional den/office room. Outside storage building 10X15 great for storage. Located close to new public park at end of street. ',
    category: 'recently-sold',
    propertyFor: 'for-sale',
  },
  {
    id: 2,
    street: '8 Bobwhite Center',
    city: 'Dallas',
    country: 'United States',
    state: 'Texas',
    price: 5946412,
    bed: 4,
    bath: 2,
    sqft: 4019,
    uniqueId: '67467651fc13ae3c43e1c270',
    image:
      'http://ap.rdcpix.com/dc056cce79810cd4113cadea6618982dl-m526987112rd-w2048_h1536.webp',
    photos: [
      { id: 1, title: 'front', image: ImgPropertyFront },
      { id: 2, title: 'side', image: ImgPropertySide },
      { id: 3, title: 'rear', image: ImgPropertyRear },
      { id: 4, title: 'yard', image: ImgPropertyYard },
    ],
    detail:
      'The house has 4 bedrooms and 2 bathrooms with ample rental potential. Qualifies for AHA program that allows $2700 month rent. Spacious room sizes, separate laundry room, huge deck on rear, additional den/office room. Outside storage building 10X15 great for storage. Located close to new public park at end of street. ',
    category: 'price-reduced',
    propertyFor: 'for-sale',
  },
  {
    id: 3,
    street: '8189 Delladonna Street',
    city: 'Rochester',
    country: 'United States',
    state: 'New York',
    price: 1657010,
    bed: 5,
    bath: 4,
    sqft: 4818,
    uniqueId: '67467651fc13ae3c43e1c271',
    image:
      'http://ap.rdcpix.com/dc056cce79810cd4113cadea6618982dl-m526987112rd-w2048_h1536.webp',
    photos: [
      { id: 1, title: 'front', image: ImgPropertyFront },
      { id: 2, title: 'side', image: ImgPropertySide },
      { id: 3, title: 'rear', image: ImgPropertyRear },
      { id: 4, title: 'yard', image: ImgPropertyYard },
    ],
    detail:
      'The house has 4 bedrooms and 2 bathrooms with ample rental potential. Qualifies for AHA program that allows $2700 month rent. Spacious room sizes, separate laundry room, huge deck on rear, additional den/office room. Outside storage building 10X15 great for storage. Located close to new public park at end of street. ',
    category: 'price-reduced',
    propertyFor: 'for-sale',
  },
  {
    id: 4,
    street: '3936 Doe Crossing Parkway',
    city: 'Richmond',
    country: 'United States',
    state: 'Virginia',
    price: 5638085,
    bed: 4,
    bath: 3,
    sqft: 4573,
    uniqueId: '67467651fc13ae3c43e1c272',
    image:
      'http://ap.rdcpix.com/dc056cce79810cd4113cadea6618982dl-m526987112rd-w2048_h1536.webp',
    photos: [
      { id: 1, title: 'front', image: ImgPropertyFront },
      { id: 2, title: 'side', image: ImgPropertySide },
      { id: 3, title: 'rear', image: ImgPropertyRear },
      { id: 4, title: 'yard', image: ImgPropertyYard },
    ],
    detail:
      'The house has 4 bedrooms and 2 bathrooms with ample rental potential. Qualifies for AHA program that allows $2700 month rent. Spacious room sizes, separate laundry room, huge deck on rear, additional den/office room. Outside storage building 10X15 great for storage. Located close to new public park at end of street. ',
    category: 'price-reduced',
    propertyFor: 'for-sale',
  },
  {
    id: 5,
    street: '08828 Lakewood Terrace',
    city: 'Salt Lake City',
    country: 'United States',
    state: 'Utah',
    price: 5099507,
    bed: 6,
    bath: 5,
    sqft: 1042,
    uniqueId: '67467651fc13ae3c43e1c273',
    image:
      'http://ap.rdcpix.com/dc056cce79810cd4113cadea6618982dl-m526987112rd-w2048_h1536.webp',
    photos: [
      { id: 1, title: 'front', image: ImgPropertyFront },
      { id: 2, title: 'side', image: ImgPropertySide },
      { id: 3, title: 'rear', image: ImgPropertyRear },
      { id: 4, title: 'yard', image: ImgPropertyYard },
    ],
    detail:
      'The house has 4 bedrooms and 2 bathrooms with ample rental potential. Qualifies for AHA program that allows $2700 month rent. Spacious room sizes, separate laundry room, huge deck on rear, additional den/office room. Outside storage building 10X15 great for storage. Located close to new public park at end of street. ',
    category: 'recommended',
    propertyFor: 'for-sale',
  },
  {
    id: 6,
    street: '5494 Mccormick Center',
    city: 'Hollywood',
    country: 'United States',
    state: 'Florida',
    price: 928866,
    bed: 4,
    bath: 4,
    sqft: 5463,
    uniqueId: '67467651fc13ae3c43e1c274',
    image:
      'http://ap.rdcpix.com/dc056cce79810cd4113cadea6618982dl-m526987112rd-w2048_h1536.webp',
    photos: [
      { id: 1, title: 'front', image: ImgPropertyFront },
      { id: 2, title: 'side', image: ImgPropertySide },
      { id: 3, title: 'rear', image: ImgPropertyRear },
      { id: 4, title: 'yard', image: ImgPropertyYard },
    ],
    detail:
      'The house has 4 bedrooms and 2 bathrooms with ample rental potential. Qualifies for AHA program that allows $2700 month rent. Spacious room sizes, separate laundry room, huge deck on rear, additional den/office room. Outside storage building 10X15 great for storage. Located close to new public park at end of street. ',
    category: 'price-reduced',
    propertyFor: 'rent',
  },
  {
    id: 7,
    street: '14 Southridge Street',
    city: 'Fort Worth',
    country: 'United States',
    state: 'Texas',
    price: 225373,
    bed: 2,
    bath: 3,
    sqft: 1162,
    uniqueId: '67467651fc13ae3c43e1c275',
    image:
      'http://ap.rdcpix.com/dc056cce79810cd4113cadea6618982dl-m526987112rd-w2048_h1536.webp',
    photos: [
      { id: 1, title: 'front', image: ImgPropertyFront },
      { id: 2, title: 'side', image: ImgPropertySide },
      { id: 3, title: 'rear', image: ImgPropertyRear },
      { id: 4, title: 'yard', image: ImgPropertyYard },
    ],
    detail:
      'The house has 4 bedrooms and 2 bathrooms with ample rental potential. Qualifies for AHA program that allows $2700 month rent. Spacious room sizes, separate laundry room, huge deck on rear, additional den/office room. Outside storage building 10X15 great for storage. Located close to new public park at end of street. ',
    category: 'land',
    propertyFor: 'for-sale',
  },
  {
    id: 8,
    street: '829 Little Fleur Terrace',
    city: 'Saint Louis',
    country: 'United States',
    state: 'Missouri',
    price: 2316218,
    bed: 1,
    bath: 3,
    sqft: 5689,
    uniqueId: '67467651fc13ae3c43e1c276',
    image:
      'http://ap.rdcpix.com/dc056cce79810cd4113cadea6618982dl-m526987112rd-w2048_h1536.webp',
    photos: [
      { id: 1, title: 'front', image: ImgPropertyFront },
      { id: 2, title: 'side', image: ImgPropertySide },
      { id: 3, title: 'rear', image: ImgPropertyRear },
      { id: 4, title: 'yard', image: ImgPropertyYard },
    ],
    detail:
      'The house has 4 bedrooms and 2 bathrooms with ample rental potential. Qualifies for AHA program that allows $2700 month rent. Spacious room sizes, separate laundry room, huge deck on rear, additional den/office room. Outside storage building 10X15 great for storage. Located close to new public park at end of street. ',
    category: 'recently-sold',
    propertyFor: 'for-sale',
  },
  {
    id: 9,
    street: '6464 Elgar Court',
    city: 'Sandy',
    country: 'United States',
    state: 'Utah',
    price: 3527530,
    bed: 3,
    bath: 4,
    sqft: 2152,
    uniqueId: '67467651fc13ae3c43e1c277',
    image:
      'http://ap.rdcpix.com/dc056cce79810cd4113cadea6618982dl-m526987112rd-w2048_h1536.webp',
    photos: [
      { id: 1, title: 'front', image: ImgPropertyFront },
      { id: 2, title: 'side', image: ImgPropertySide },
      { id: 3, title: 'rear', image: ImgPropertyRear },
      { id: 4, title: 'yard', image: ImgPropertyYard },
    ],
    detail:
      'The house has 4 bedrooms and 2 bathrooms with ample rental potential. Qualifies for AHA program that allows $2700 month rent. Spacious room sizes, separate laundry room, huge deck on rear, additional den/office room. Outside storage building 10X15 great for storage. Located close to new public park at end of street. ',
    category: 'recently-sold',
    propertyFor: 'rent',
  },
  {
    id: 10,
    street: '567 Arapahoe Drive',
    city: 'Portland',
    country: 'United States',
    state: 'Oregon',
    price: 5368397,
    bed: 6,
    bath: 1,
    sqft: 5532,
    uniqueId: '67467651fc13ae3c43e1c278',
    image:
      'http://ap.rdcpix.com/dc056cce79810cd4113cadea6618982dl-m526987112rd-w2048_h1536.webp',
    photos: [
      { id: 1, title: 'front', image: ImgPropertyFront },
      { id: 2, title: 'side', image: ImgPropertySide },
      { id: 3, title: 'rear', image: ImgPropertyRear },
      { id: 4, title: 'yard', image: ImgPropertyYard },
    ],
    detail:
      'The house has 4 bedrooms and 2 bathrooms with ample rental potential. Qualifies for AHA program that allows $2700 month rent. Spacious room sizes, separate laundry room, huge deck on rear, additional den/office room. Outside storage building 10X15 great for storage. Located close to new public park at end of street. ',
    category: 'new-listings',
    propertyFor: 'rent',
  },
  {
    id: 11,
    street: '86 Mcbride Parkway',
    city: 'Jackson',
    country: 'United States',
    state: 'Mississippi',
    price: 613928,
    bed: 3,
    bath: 1,
    sqft: 2622,
    uniqueId: '67467651fc13ae3c43e1c279',
    image:
      'http://ap.rdcpix.com/dc056cce79810cd4113cadea6618982dl-m526987112rd-w2048_h1536.webp',
    photos: [
      { id: 1, title: 'front', image: ImgPropertyFront },
      { id: 2, title: 'side', image: ImgPropertySide },
      { id: 3, title: 'rear', image: ImgPropertyRear },
      { id: 4, title: 'yard', image: ImgPropertyYard },
    ],
    detail:
      'The house has 4 bedrooms and 2 bathrooms with ample rental potential. Qualifies for AHA program that allows $2700 month rent. Spacious room sizes, separate laundry room, huge deck on rear, additional den/office room. Outside storage building 10X15 great for storage. Located close to new public park at end of street. ',
    category: 'land',
    propertyFor: 'rent',
  },
  {
    id: 12,
    street: '52 Crescent Oaks Parkway',
    city: 'Miami',
    country: 'United States',
    state: 'Florida',
    price: 2299977,
    bed: 3,
    bath: 2,
    sqft: 3705,
    uniqueId: '67467651fc13ae3c43e1c27a',
    image:
      'http://ap.rdcpix.com/dc056cce79810cd4113cadea6618982dl-m526987112rd-w2048_h1536.webp',
    photos: [
      { id: 1, title: 'front', image: ImgPropertyFront },
      { id: 2, title: 'side', image: ImgPropertySide },
      { id: 3, title: 'rear', image: ImgPropertyRear },
      { id: 4, title: 'yard', image: ImgPropertyYard },
    ],
    detail:
      'The house has 4 bedrooms and 2 bathrooms with ample rental potential. Qualifies for AHA program that allows $2700 month rent. Spacious room sizes, separate laundry room, huge deck on rear, additional den/office room. Outside storage building 10X15 great for storage. Located close to new public park at end of street. ',
    category: 'open-houses',
    propertyFor: 'rent',
  },
  {
    id: 13,
    street: '200 Lakeland Center',
    city: 'Des Moines',
    country: 'United States',
    state: 'Iowa',
    price: 2661100,
    bed: 4,
    bath: 2,
    sqft: 1578,
    uniqueId: '67467651fc13ae3c43e1c27b',
    image:
      'http://ap.rdcpix.com/dc056cce79810cd4113cadea6618982dl-m526987112rd-w2048_h1536.webp',
    photos: [
      { id: 1, title: 'front', image: ImgPropertyFront },
      { id: 2, title: 'side', image: ImgPropertySide },
      { id: 3, title: 'rear', image: ImgPropertyRear },
      { id: 4, title: 'yard', image: ImgPropertyYard },
    ],
    detail:
      'The house has 4 bedrooms and 2 bathrooms with ample rental potential. Qualifies for AHA program that allows $2700 month rent. Spacious room sizes, separate laundry room, huge deck on rear, additional den/office room. Outside storage building 10X15 great for storage. Located close to new public park at end of street. ',
    category: 'open-houses',
    propertyFor: 'rent',
  },
  {
    id: 14,
    street: '1981 1st Junction',
    city: 'Seattle',
    country: 'United States',
    state: 'Washington',
    price: 3821539,
    bed: 1,
    bath: 5,
    sqft: 2726,
    uniqueId: '67467651fc13ae3c43e1c27c',
    image:
      'http://ap.rdcpix.com/dc056cce79810cd4113cadea6618982dl-m526987112rd-w2048_h1536.webp',
    photos: [
      { id: 1, title: 'front', image: ImgPropertyFront },
      { id: 2, title: 'side', image: ImgPropertySide },
      { id: 3, title: 'rear', image: ImgPropertyRear },
      { id: 4, title: 'yard', image: ImgPropertyYard },
    ],
    detail:
      'The house has 4 bedrooms and 2 bathrooms with ample rental potential. Qualifies for AHA program that allows $2700 month rent. Spacious room sizes, separate laundry room, huge deck on rear, additional den/office room. Outside storage building 10X15 great for storage. Located close to new public park at end of street. ',
    category: 'new-listings',
    propertyFor: 'rent',
  },
  {
    id: 15,
    street: '70239 Farwell Parkway',
    city: 'Lincoln',
    country: 'United States',
    state: 'Nebraska',
    price: 988729,
    bed: 2,
    bath: 1,
    sqft: 2879,
    uniqueId: '67467651fc13ae3c43e1c27d',
    image:
      'http://ap.rdcpix.com/dc056cce79810cd4113cadea6618982dl-m526987112rd-w2048_h1536.webp',
    photos: [
      { id: 1, title: 'front', image: ImgPropertyFront },
      { id: 2, title: 'side', image: ImgPropertySide },
      { id: 3, title: 'rear', image: ImgPropertyRear },
      { id: 4, title: 'yard', image: ImgPropertyYard },
    ],
    detail:
      'The house has 4 bedrooms and 2 bathrooms with ample rental potential. Qualifies for AHA program that allows $2700 month rent. Spacious room sizes, separate laundry room, huge deck on rear, additional den/office room. Outside storage building 10X15 great for storage. Located close to new public park at end of street. ',
    category: 'open-houses',
    propertyFor: 'rent',
  },
  {
    id: 16,
    street: '552 Memorial Junction',
    city: 'Pueblo',
    country: 'United States',
    state: 'Colorado',
    price: 1638240,
    bed: 5,
    bath: 3,
    sqft: 1347,
    uniqueId: '67467651fc13ae3c43e1c27e',
    image:
      'http://ap.rdcpix.com/dc056cce79810cd4113cadea6618982dl-m526987112rd-w2048_h1536.webp',
    photos: [
      { id: 1, title: 'front', image: ImgPropertyFront },
      { id: 2, title: 'side', image: ImgPropertySide },
      { id: 3, title: 'rear', image: ImgPropertyRear },
      { id: 4, title: 'yard', image: ImgPropertyYard },
    ],
    detail:
      'The house has 4 bedrooms and 2 bathrooms with ample rental potential. Qualifies for AHA program that allows $2700 month rent. Spacious room sizes, separate laundry room, huge deck on rear, additional den/office room. Outside storage building 10X15 great for storage. Located close to new public park at end of street. ',
    category: 'recently-sold',
    propertyFor: 'rent',
  },
  {
    id: 17,
    street: '3355 Donald Trail',
    city: 'Pinellas Park',
    country: 'United States',
    state: 'Florida',
    price: 3614659,
    bed: 3,
    bath: 5,
    sqft: 2013,
    uniqueId: '67467651fc13ae3c43e1c27f',
    image:
      'http://ap.rdcpix.com/dc056cce79810cd4113cadea6618982dl-m526987112rd-w2048_h1536.webp',
    photos: [
      { id: 1, title: 'front', image: ImgPropertyFront },
      { id: 2, title: 'side', image: ImgPropertySide },
      { id: 3, title: 'rear', image: ImgPropertyRear },
      { id: 4, title: 'yard', image: ImgPropertyYard },
    ],
    detail:
      'The house has 4 bedrooms and 2 bathrooms with ample rental potential. Qualifies for AHA program that allows $2700 month rent. Spacious room sizes, separate laundry room, huge deck on rear, additional den/office room. Outside storage building 10X15 great for storage. Located close to new public park at end of street. ',
    category: 'open-houses',
    propertyFor: 'rent',
  },
  {
    id: 18,
    street: '815 Parkside Park',
    city: 'Philadelphia',
    country: 'United States',
    state: 'Pennsylvania',
    price: 2771705,
    bed: 1,
    bath: 3,
    sqft: 1707,
    uniqueId: '67467651fc13ae3c43e1c280',
    image:
      'http://ap.rdcpix.com/dc056cce79810cd4113cadea6618982dl-m526987112rd-w2048_h1536.webp',
    photos: [
      { id: 1, title: 'front', image: ImgPropertyFront },
      { id: 2, title: 'side', image: ImgPropertySide },
      { id: 3, title: 'rear', image: ImgPropertyRear },
      { id: 4, title: 'yard', image: ImgPropertyYard },
    ],
    detail:
      'The house has 4 bedrooms and 2 bathrooms with ample rental potential. Qualifies for AHA program that allows $2700 month rent. Spacious room sizes, separate laundry room, huge deck on rear, additional den/office room. Outside storage building 10X15 great for storage. Located close to new public park at end of street. ',
    category: 'recommended',
    propertyFor: 'for-sale',
  },
  {
    id: 19,
    street: '72 Continental Park',
    city: 'Richmond',
    country: 'United States',
    state: 'Virginia',
    price: 3463530,
    bed: 4,
    bath: 3,
    sqft: 3040,
    uniqueId: '67467651fc13ae3c43e1c281',
    image:
      'http://ap.rdcpix.com/dc056cce79810cd4113cadea6618982dl-m526987112rd-w2048_h1536.webp',
    photos: [
      { id: 1, title: 'front', image: ImgPropertyFront },
      { id: 2, title: 'side', image: ImgPropertySide },
      { id: 3, title: 'rear', image: ImgPropertyRear },
      { id: 4, title: 'yard', image: ImgPropertyYard },
    ],
    detail:
      'The house has 4 bedrooms and 2 bathrooms with ample rental potential. Qualifies for AHA program that allows $2700 month rent. Spacious room sizes, separate laundry room, huge deck on rear, additional den/office room. Outside storage building 10X15 great for storage. Located close to new public park at end of street. ',
    category: 'open-houses',
    propertyFor: 'for-sale',
  },
  {
    id: 20,
    street: '80 Service Way',
    city: 'Baltimore',
    country: 'United States',
    state: 'Maryland',
    price: 3255267,
    bed: 3,
    bath: 2,
    sqft: 4793,
    uniqueId: '67467651fc13ae3c43e1c282',
    image:
      'http://ap.rdcpix.com/dc056cce79810cd4113cadea6618982dl-m526987112rd-w2048_h1536.webp',
    photos: [
      { id: 1, title: 'front', image: ImgPropertyFront },
      { id: 2, title: 'side', image: ImgPropertySide },
      { id: 3, title: 'rear', image: ImgPropertyRear },
      { id: 4, title: 'yard', image: ImgPropertyYard },
    ],
    detail:
      'The house has 4 bedrooms and 2 bathrooms with ample rental potential. Qualifies for AHA program that allows $2700 month rent. Spacious room sizes, separate laundry room, huge deck on rear, additional den/office room. Outside storage building 10X15 great for storage. Located close to new public park at end of street. ',
    category: 'recommended',
    propertyFor: 'for-sale',
  },
];
